In [ ]:
#Data.csv

**Step 1: Importing the libraries**

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


**Step 2: Importing dataset**

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/assignment 11 -16/Data.csv")

In [ ]:
df.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

**Step 3: Handling the missing data**

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


In [ ]:
df.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [ ]:
df = pd.DataFrame(df)
df.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [ ]:
#here the missing values turn to be nan or false 
df.notnull()

Country    Age  Salary  Purchased
0     True   True    True       True
1     True   True    True       True
2     True   True    True       True
3     True   True    True       True
4     True   True   False       True
5     True   True    True       True
6     True  False    True       True
7     True   True    True       True
8     True   True    True       True
9     True   True    True       True

**Step 4: Encoding categorical data**

In [ ]:
df.head(2)

Country   Age   Salary Purchased
0  France  44.0  72000.0        No
1   Spain  27.0  48000.0       Yes

In [ ]:
#here lets encode the data using sklearn label encoder 
from sklearn.preprocessing import LabelEncoder
LE = LabelEncoder()
df["Purchased"]=LE.fit_transform(df["Purchased"])
df["Purchased"].unique()

array([0, 1])

**Step 5: Creating a dummy variable**

In [ ]:
pd.get_dummies(df)

Country   Age   Salary  Purchased
0        0  44.0  72000.0          0
1        2  27.0  48000.0          1
2        1  30.0  54000.0          0
3        2  38.0  61000.0          0
4        1  40.0      NaN          1
5        0  35.0  58000.0          1
6        2   NaN  52000.0          0
7        0  48.0  79000.0          1
8        1  50.0  83000.0          0
9        0  37.0  67000.0          1

In [ ]:
X = df.iloc[:,[1,2]]
X.shape

(10, 2)

In [ ]:
y = df["Purchased"].values
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

**Step 6: Splitting the datasets into training sets and Test sets**

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.25,random_state =0)

**Step 7: Feature Scaling**

In [ ]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
X_train

array([[-0.17494534,  0.44897083],
       [-1.67447681, -1.41706417],
       [        nan, -1.0242147 ],
       [ 1.47453928,  1.62751925],
       [-0.02499219, -0.14030338],
       [ 0.87472669,  0.94003267],
       [-0.47485163, -0.43494049]])

In [ ]:
X_test

array([[-1.22461737, -0.82778996],
       [ 1.77444557,  2.02036872],
       [ 0.2749141 ,         nan]])